### ISSUE TITLE
[Bug]: Public LSD bans players taking too much

### ISSUE THREAD

**Issue by RG2Kelvin** [fayynt/issues#34] opened 2023-11-03 00:39 UTC
### Is there an existing issue for this?

- [X] I have searched for existing issues

### Description

taking public lsd to gain max amour bans players hitting 100 

### Expected behaviour

drug to stop at LDN armour limit 

### Steps to reproduce

spawn lsd and take till banned

### Discord ID

575632373077770260

**Comment by FellaHighOnaBoat** [comment] 2024-01-02 17:00
@fayynt fixed?

**Comment by fayynt** [comment] 2024-01-02 17:01
> @fayynt fixed?

Doing 😎

**Comment by fayynt** [comment] 2024-02-16 22:05
Duplicate of #82 so will close for now

**Closed by fayynt** 2024-02-16 22:05 UTC
Labels: bug
